### ISSUE TITLE
index.php userlist hash issue

### ISSUE THREAD

**Issue by deepend-tildeclub** [tildeclub/site#39]
index.php seems to selectively show/not show pages of the hashes in the list.  
051b45fb2da9b15c523dfafd2a1dd33cc8b54e87   http://tilde.club/~trisk/
and 
b0eb2bf442e52b98714456b2f8a6662ba4c1f443   http://tilde.club/~entrez/
for example are hashes of pages that shouldn't show in the list but do.

**Comment by deepend-tildeclub** [comment]
9da422e8759799cce29327024fc77b6aa2ace484 is another one.

**Comment by benharri** [comment]
trisk and entrez are no longer showing on the homepage

**Comment by deepend-tildeclub** [comment]
Hmm.  Maybe browser caching was the issue then.  
Or something to do with updating the OS fixed something ?
